project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - syllabus.qmd
    - homework/*.qmd
    - slides/*.qmd
website:
  title: "Stat 850: Computing Tools for Statisticians"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://srvanderplas.github.io/stat-computing-r-python/
        text: Textbook
      - href: syllabus.pdf
        text: Syllabus
  google-analytics: "G-KQ9CCFY6LV"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  cache: true
  freeze: auto  # re-render only when source changes
